[COIN-795] Enhance compatibility for Apple Silicon and upgrade kubectl to 1.25.13
banksalad/helm-bazel-rules pull request #2
Opened 2023-08-25 07:50 UTC by hoonahn

### Changes
- `_arm64` postfix를 붙인 toolchain을 추가하여 Apple Silicon(M1) 호환성 개선
- kubectl 버전이 1.16으로 너무 낮아서 1.25.13으로 업그레이드
 
  - 참고: https://www.downloadkubernetes.com/

2023-08-28 04:06 UTC, hoonahn commented
q; `_arm64` 붙인 것처럼 `_amd64`를 붙이는게 덜 헷갈릴까요? @moonk-banksalad

2023-08-28 04:42 UTC, moonk-banksalad requested changes

2023-08-28 04:42 UTC, moonk-banksalad commented on toolchains/helm-3/BUILD
> +        "@platforms//cpu:x86_64",
이게 cpu:arm64가 되어야 할 듯?

2023-08-28 04:42 UTC, moonk-banksalad commented on toolchains/helm-3/BUILD
> +        "@platforms//cpu:x86_64",
마찬가지입니다.

2023-08-28 04:42 UTC, moonk-banksalad commented on toolchains/helm-3/BUILD
>      target_compatible_with = [
여기도 CPU가 들어가야 합니다.

2023-08-28 04:42 UTC, moonk-banksalad commented on toolchains/helm-3/BUILD
> +        "@platforms//os:osx",
여기도 추가

2023-08-28 04:42 UTC, moonk-banksalad commented on toolchains/kubectl/BUILD
> +        "@platforms//cpu:x86_64",
여기도 CPU 수정

2023-08-28 04:42 UTC, moonk-banksalad commented on toolchains/kubectl/BUILD
> +        "@platforms//os:linux",
여기도 CPU 수정

2023-08-28 04:42 UTC, moonk-banksalad commented on toolchains/kubectl/BUILD
> +        "@platforms//os:osx",
여기도 추가

2023-08-28 06:47 UTC, moonk-banksalad commented on toolchains/helm-3/BUILD
> +        "@platforms//cpu:x86_64",
참고로 Bazel에서 사용할 수 있는 @platforms 값들은 여기에 정의되어 있습니다.
https://github.com/bazelbuild/platforms/blob/main/cpu/BUILD

2023-08-28 06:48 UTC, moonk-banksalad commented
> q; _arm64 붙인 것처럼 _amd64를 붙이는게 덜 헷갈릴까요? @moonk-banksalad

굳이 붙일 필요는 없을 것 같습니다. 코드 수정도 많이 해야 하고...

2023-08-31 01:11 UTC, hoonahn commented on toolchains/kubectl/BUILD
> +        "@platforms//os:osx",
[089ef2e](https://github.com/banksalad/helm-bazel-rules/pull/2/commits/089ef2e13308a063a3d43e09b0150a420b46ee68)

2023-08-31 01:12 UTC, hoonahn commented on toolchains/helm-3/BUILD
> +        "@platforms//cpu:x86_64",
[089ef2e](https://github.com/banksalad/helm-bazel-rules/pull/2/commits/089ef2e13308a063a3d43e09b0150a420b46ee68)

2023-08-31 06:32 UTC, hoonahn commented
<img width="838" alt="image" src="https://github.com/banksalad/helm-bazel-rules/assets/12765404/de1b1b69-5665-4433-95ba-2e78723b5541">

드디어 M1에서 bazel build를 성공했습니다 ㅎ..

2023-08-31 07:02 UTC, moonk-banksalad commented
Integration tests 만 고치면 될 것 같습니다!

2023-08-31 07:24 UTC, hoonahn commented
> Integration tests 만 고치면 될 것 같습니다! 에러를 보니 새로운 yq 바이너리가 깨진듯? line 43: external/yq_v4.35.1_linux/file/downloaded: cannot execute binary file: Exec format error

넵 exec 가능한 것으로 바꿨습니다 ㅎㅎ

2023-09-01 01:56 UTC, hoonahn commented
PR상에 변경사항과 어떤 관계가 있는지 모를 에러가 계속 발생하네요 😵 
짐작이 가는 부분이 있으실까요? cc @moonk-banksalad 
```
Error:         	            	ERROR: /home/runner/work/helm-bazel-rules/helm-bazel-rules/tests/charts/nginx/BUILD:7:11: Action tests/charts/nginx/nginx.tgz failed: (Exit 1): nginx_chart_helm_bash failed: error executing command bazel-out/k8-fastbuild/bin/tests/charts/nginx/nginx_chart_helm_bash
Error:         	            	Error: 1:1: invalid input text "w"
```

2023-09-01 08:13 UTC, hoonahn commented
[이슈 공유]

기존 upstream에서 사용하던 yq의 버전이 v2이었는데, 이 경우 apple silicon과 호환되는 패키지가 없었어서 최신 v4 버전으로 올렸는데 기존 yq에서 `w`라는 커맨드를 사용하던게 v4에서는 변경이 되었었던 것이었고 그래서 에러가 발생했습니다.
- https://mikefarah.gitbook.io/yq/upgrading-from-v3#updating-writing-documents

v3까지는 유지되었던 것으로 보여서 v3로 내리려고 하니 v3에서도 apple silicon과 호환되는 패키지가 없어서... apple silicon에서 사용하기 위해서는 yq를 v4로 올려야했고, 패키지 내에서 yq를 사용하는 곳 중 deprecated 커맨드를 사용하는 곳들을 migration 가이드에 따라 변경해보고 있습니다. cc. @moonk-banksalad, (도움 주신) @namkwangwoo 
[219cc9c](https://github.com/banksalad/helm-bazel-rules/pull/2/commits/219cc9c1945f87184e801afdf981d1cc01d116c1)

2023-09-04 00:46 UTC, moonk-banksalad requested changes

2023-09-04 00:46 UTC, moonk-banksalad commented on helm/helm-chart-package.sh.tpl
> +        REPO_URL=$({YQ_PATH} "{VALUES_REPO_YAML_PATH}" {CHART_VALUES_PATH})
yq r 명령어에 대한 변경시에도 selector는 "."을 붙여주여야 합니다.
https://mikefarah.gitbook.io/yq/upgrading-from-v3

2023-09-04 00:46 UTC, moonk-banksalad commented on helm/helm-chart-package.sh.tpl
> +        REPO_URL=$({YQ_PATH} "{VALUES_REPO_YAML_PATH}" {CHART_VALUES_PATH})
그리고 굳이 ""를 사용할 필요가 있나요?

2023-09-04 00:46 UTC, moonk-banksalad commented on helm/helm-chart-package.sh.tpl
> +        {YQ_PATH} -i '.{VALUES_REPO_YAML_PATH} = $REPO_URL$REPO_SUFIX' {CHART_VALUES_PATH}
굳이 {}를 제거할 필요가 있나요? ${REPO_URL} -> $REPO_URL

2023-09-04 05:47 UTC, hoonahn commented
yq v4에서 env를 가져다 쓰는 것도 다른 방식으로 변동된 것 같습니다 ㅜ
그래서 env 값을 못가져와서 계속 이상하게 ci가 깨졌던 것도 있네요.

https://mikefarah.gitbook.io/yq/operators/env-variable-operators

cc. @moonk-banksalad @namkwangwoo

2023-09-04 05:50 UTC, hoonahn commented on helm/helm-chart-package.sh.tpl
> +        {YQ_PATH} -i '.{VALUES_REPO_YAML_PATH} = $REPO_URL$REPO_SUFIX' {CHART_VALUES_PATH}
수정했습니다!

2023-09-04 05:50 UTC, hoonahn commented on helm/helm-chart-package.sh.tpl
> +        REPO_URL=$({YQ_PATH} "{VALUES_REPO_YAML_PATH}" {CHART_VALUES_PATH})
수정했습니다!

2023-09-04 06:56 UTC, moonk-banksalad approved these changes

2023-09-04 06:57 UTC, namkwangwoo approved these changes
lgtm

2023-09-04 08:00 UTC, merged